identifier: nice_nano_v2
name: nice!nano v2
type: mcu
arch: arm
toolchain:
  - gnuarmemb
  - xtools
  - zephyr
ram: 256
flash: 1024
supported:
  - adc
  - usb_device
  - ble
  - ieee802154
  - pwm
  - watchdog
  - gpio
  - i2c
  - spi
